/**
 * Provider-agnostic TTS adapter interface.
 *
 * All TTS providers (OpenAI, ElevenLabs, mock) implement this.
 * No framework imports — usable from Next.js routes, Lambda, CLI, anywhere.
 */

export interface TtsOptions {
  /** Voice identifier (provider-specific; adapters map to a sensible default) */
  voice?: string;
  /** Output audio format hint (provider-specific) */
  format?: string;
}

/**
 * A TTS adapter turns a stream of text fragments into a stream of audio bytes.
 * Streaming both directions lets audio playback begin before the full text
 * has been generated by the LLM.
 */
export interface TtsAdapter {
  /** The provider this adapter represents. */
  readonly provider: string;

  /**
   * Streams text (async iterable of fragments) into audio byte chunks.
   */
  streamTextToSpeech(
    textStream: AsyncIterable<string>,
    options?: TtsOptions,
  ): AsyncIterable<Uint8Array>;
}
